
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-k8s
  template:
    metadata:
      labels:
        app: project-k8s
    spec:
      containers:
      - name: weather-app
        image: hassanamohamed/weather-app
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: project-k8s
spec:
  type: LoadBalancer 
  selector:
    app: project-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000 #container port
    nodePort: 30080